### ISSUE TITLE
Example is pretty much confusing

### ISSUE THREAD

**Issue by pzmudzinski** [RxSwiftCommunity/RxFlow#104]
I am doing some tests against this framework since navigation was always tricky in iOS apps. 
First of all what is really off-putting is the fact example code will not even compile against current published version (1.6.2).
e.g. this line: `return .one(flowContributor: .contribute(withNextPresentable: viewController, withNextStepper: viewController.viewModel))`

Another thing is description and idea behind `Step` which is put as: 

> Steps are seen like some navigation states spread across the application. 

I would imagine that is represents some kind of enum with cases like `login, movieList, movieDetails`. 
There might be some *actions* which modify it's state, e.g. successful auth request leads to `movieList` or maybe to "You have to verify your email to use this service" screen based on business logic.  

Calling `pickMovie` or using VM's input like `button.rx.tap.bind(to: viewModel.selectionInput)` would lead to `movieDetails`. 

However, example step is:
```
enum DemoStep: Step {
    case movieList
    case moviePicked (withMovieId: Int)
    case castPicked (withCastId: Int)
```

Which mixes idea of navigation state (`movieList`) with sense of action which modifies navigation state (`moviePicked`). 
What does it mean that navigation is in `moviePicked` state? Does it mean it's in middle of animation between pushing from `movieList` to `movieDetails`? Does it mean it's in `movieDetails` (which isn't listed for some reason?)? What does `settingsDone` state means? Does it mean user is in confirmation screen? Does it mean user got back from settings to... where? 

Do not want to be super grumpy here, just letting you know about my thoughts after seeing and trying your project for first time. Hopefully it will be helpful in any minimal way 👍

**Comment by twittemb** [comment]
Hi @pzmudzinski 

You make very good points here. 

First, the README you mention is the one for version under development (develop branch): RxFlow 2.0, so it is normal that code samples don't compile with RxFlow 1.6.2. The README corresponding to that version is the one on the master branch (which is now the default branch of the repo to make it clearer).

For the semantic issues you're pointing, I will take the time to address them in order to make it clearer that a Step should not be related to "what's coming next" in terms of navigation. In that way, a Step is not really a Navigation State, but an Intent saying "Hey, I'm done here, please mister Coordinator react to that fact and decide where to go next".

I'll get back to you soon.

Thanks.

**Comment by pzmudzinski** [comment]
Yes I was under impression it represents an action which leads to new navigation state. In another part of example you presented listening for state with this snippet: 
```
        coordinator.rx.didNavigate.subscribe(onNext: { (flow, step) in
            print ("did navigate to flow=\(flow) and step=\(step)")
        }).disposed(by: self.disposeBag)
```
If flow represents some isolated area of app (like Sign-Up flow) and step represents action (like "enteredVerificationCode") then how do you actually listen for user's current screen? 
This snippet would print "did navigate to flow=SignUp and step=enteredVerificationCode" which does not say much. 

Another questions:  
1. Does `RxFlow` requires overriding default back buttons or we can use default ones without messing with coordinator's state?  
2. Does swipe to go back in `UINavigationController` works out of the box or it will mess things up?

**Comment by pzmudzinski** [comment]
Yes, things are more clear now. Thanks!
