### ISSUE TITLE
RxFlowStep seems to be quite useless

### ISSUE THREAD

**Issue by MortyMerr** [RxSwiftCommunity/RxFlow#105]
I think every developer of this framework always has line `guard let step = step as? MyStep else { return .none }` at the beginning of every `navigate(to:)` method. Even if there is a built-in enum with suitable steps - it is easier to just copy them to my own enum and use it. 

I don't think that two switches (one with my steps enum, second with RxFlowStep) is a nice idea either.

Built-in enum makes API even more complicated and i can't see any pros in it. Do you really think, that user needs ur steps?

**Comment by twittemb** [comment]
RxFlowStep is in its early stage in terms of conception. I haven't even described an example in the demo app in order to not disturb RxFlow users for now.

It might be useful for describing pretty common and reusable Flows ... perhaps it might not be useful at all ! Who knowns ... but don't be too quick to judge please.
