### ISSUE TITLE
Consistent Import Problems - This Library won't Build - No such module RxFlow, in Demo and Real Project

### ISSUE THREAD

**Issue by sirvon** [RxSwiftCommunity/RxFlow#11]
Everytime, i try to build a Demo Project or a Project I create with RxFlow, I get

```swift
No module 'RxFlow'

```

I'm using cocoapods 

```ruby
  pod 'RxFlow'
```

It took me a little bit to understand the concepts behind this library and integrate them into my
projects, the time has come to build. But, I am now facing issues getting RxFlow to import.

I have tried using cocoapods and Carthage, on fresh projects, existing projects and the demo project, to no avail.

**Comment by twittemb** [comment]
Hi @sirvon 

I will do 1 single page app with Carthage and 1 with CocoaPods and see what is going on. I won't let you struggle with it 👍

I will keep you informed shortly.

Thibault.

**Comment by twittemb** [comment]
@sirvon 

I've made 2 simple apps. One with Carthage and one with CocoaPods. Can you give it a try ?
* https://github.com/twittemb/RxFlowCarthageDemo (carthage update --platform iOS)
* https://github.com/twittemb/RxFlowPodsDemo (pod update and then pod install)

I have tested these apps both on simulator and on true device (iPhone X).

To be honest, I had once the Warning about "No module RxFlow", but I cleaned my DerivedData and then it was OK.

Please keep me informed, because if you have this issue it means other people have it too.

Thanks.

**Comment by sirvon** [comment]
Thank You for your feedback.

I will try those demos and clean my dd.
And let you know.

**Comment by sirvon** [comment]
I downloaded both demos to my download folder.
And ran both, everything works great !
 
I cleared my derived data, like I always do. I even have a bash alias for it.
I cleared cocoapods and reinit and run pod install.

And my projects now work with RxFlow. 

Thanks!

**Comment by sirvon** [comment]
This library is still starting to not building again.

The fact that this error happens at build time after coding and then expecting to see
results, is a bummer for this library.

Can you help me find the real problem in why this library is having import problems?

**Comment by twittemb** [comment]
Hi @sirvon 

Sure I will help you. I understand that is a big issue for you. I will investigate on that right away.

**Comment by sirvon** [comment]
thank you, sir. for your prompt assistance !

**Comment by sirvon** [comment]
all fixed. my error!
