### ISSUE TITLE
Strange behaviour with UIPageViewController

### ISSUE THREAD

**Issue by MortyMerr** [RxSwiftCommunity/RxFlow#117]
I reviewed issues history and see many discussions about `UIPageViewController`. However, I would like to raise that question again.

Here is a sample project: https://github.com/MortyMerr/RxFlowBug

After changing active controller (swipe left, swipe right) steps are not being handled. Obviously, it's because of `rxDismissed` behavior

If you think this is ok, please feel free to close the issue. 
IMO this is unexpected behavior, it can confuse users. Moreover, it was working with 1.6.0 and multiple NextFlowItem
I am trying to use `.multiple(flowContributor:)`, but it blocks steps. I have to use `CompositeStepper` as a hack.

The main advantage of RxFlow for me is that unexpected steps won't be handled. If `ViewController` is hidden, its steps should be blocked. However, with `CompositeStepper` i can't achieve these guarantees. 

What do you think?

**Comment by rynecheow** [comment]
@twittemb Can we look at a solution to this, starting with a suggestion that @MortyMerr has got?

**Comment by lihao6485** [comment]
I have tried to fix this issue by adding an optional parent presentable, so if the parent is provided, we will monitor the parent `rxDismissed` instead of the child one. 

Here is the detailed implementation: https://github.com/lihao6485/RxFlow/commit/4f8c9897da7674d92388640051bf2d7df4b84491

The idea is we should observe the parent (UIPageViewController) `rxDismissed` instead of the child.

Do you guys think this could be a proper solution for this issue? @MortyMerr @rynecheow @MortyMerr

**Comment by rynecheow** [comment]
@lihao6485 Able to create a PR from the fork for review?

**Comment by twittemb** [comment]
The PR is under review ... hope to merge it tomorrow. Thanks.

**Comment by twittemb** [comment]
PR https://github.com/RxSwiftCommunity/RxFlow/pull/157 has been merged. There is an example in the demo app. Thanks to @lihao6485 for the contribution. I guess he can help you guys if you have issues with his example.

I will close this issue until further needs appear regarding UIPageViewControllers.
