### ISSUE TITLE
The struct 'Flowable' makes me confused

### ISSUE THREAD

**Issue by wsof401** [RxSwiftCommunity/RxFlow#13]
`'Flowable'` looks like a protocol that describe some thing can flow

**Comment by twittemb** [comment]
Hi @wsof401 

I agree with you. Usually, names in "able" are used for protocol that can "do" something.
Naming is not easy.

In my mind a Flowable is something that participate to the Flow lifetime, so that made sense to be name in "able" (although it is not a Protocol)

Do you have other ideas for a name ? It could be:

- FlowItem
- FlowBuilder

**Comment by sirvon** [comment]
Just because you said FlowBuilder, I understand the code more now.

**Comment by twittemb** [comment]
Hi

And what about: FlowAction. It seems to fit event better because FlowBuilder means that it will build something ... which a it doest not in fact. It holds 2 references on things that will help build a Flow.

**Comment by wsof401** [comment]
@twittemb

`Flowable` is now using to describe the next navigation item to coordinator

 But naming of `Any Action` should not only expression a single behavior, it should be a series of behaviors,  Just like RxSwift's ObservableType, It emits uncertain counts event.

`FlowProvider` or `PresenterProvider` or `FlowBuilder` may be more suitable if it is just used for describing the navigation relation between flows.

**Comment by twittemb** [comment]
@wsof401 

My problem with FlowBuilder / FlowProvider is that it means that it we build another Flow. But it is not the case ... it helps to build steps inside the Flow and eventually but not necessarily other new Flows as well.

I'd like to find a name that would mean: "Contribute to the progress in the flow with this next presentable and this next stepper" ! not that easy :-)

It could be: NavigationItem (as the function is called navigate(to:) it could make sense)

What do you think ?

**Comment by twittemb** [comment]
@wsof401 @sirvon 

I have just pushed on develop a version with the name NavigationItem. I think it is a reasonable choice and better than Flowable in anyway.

I close this issue.

**Comment by sirvon** [comment]
Now that there is discussion around Flowable, I understand what's going more.
Even NavigationItem isn't really fitting.

You said the Flowable is a helper to the Flow.
Its like a carry case for the flows thats about to happen or not.

And I can see how FlowBuilder is not fitting aswell.

FlowHelper, NextFlows, NextFlowable

the next part helps the understanding because the parameter names have next as well.

Flowable / NavigationItem should imply something like progression and carrying forward

**Comment by twittemb** [comment]
Could it be NextNavigationItem ?

**Comment by sirvon** [comment]
that works, NextItems...
Navigation bothers me because of the other uses throughout iOS.
but the Next part for sure helps bring out what it does.

**Comment by twittemb** [comment]
I agree about Navigation ... it could be misunderstood because of UINavigationXXX

NextFlowItem seems right no ?

**Comment by sirvon** [comment]
thats its!

**Comment by twittemb** [comment]
NextFlowItem is implemented on develop.

I close this issue ... again 😀

**Comment by wsof401** [comment]
@sirvon 

Better than flowable, but also has various,  Item, Step are both like the minimum atom in work flow.
like @twittemb said, Naming is not easy,  `NextFlowItem` is OK
Shall we add a flow chat for describing each item‘s responsibility?

**Comment by twittemb** [comment]
@wsof401 

There is already a list of each concept in the Readme file, it should be enough to understand the whole thing don't you think ?

- **Flow**: each **Flow** defines a navigation area within your application. This is the place where you declare the navigation actions (such as presenting a UIViewController or another Flow)
- **Step**: each **Step** is a navigation state in your application. Combinaisons of **Flows** and **Steps** describe all the possible navigation actions. A **Step** can even embed inner values (such as Ids, URLs, ...) that will be propagated to screens declared in the **Flows**
- **Stepper**: it can be anything that can emit **Steps**. **Steppers** will be responsible for triggering every navigation actions within the **Flows**
- **Presentable**: it is an abstraction of something that can be presented (basically **UIViewController** and **Flow** are **Presentable**). **Presentables** offer Reactive observables that the **Coordinator** will subscribe to in order to handle **Flow Steps** in a UIKit compliant way
- **NextFlowItem**: it is a simple data structure that combines a **Presentable** and a **stepper**. It tells the **Coordinator** what will be the next thing that will produce new **Steps** in your Reactive mechanism
- **Coordinator**: once the developer has defined the suitable combinations of **Flows** and **Steps** representing the navigation possibilities, the job of the **Coordinator** is to mix these combinaisons in a consistent way.
