### ISSUE TITLE
Combine Support?

### ISSUE THREAD

**Issue by paulmeyerle** [RxSwiftCommunity/RxFlow#135]
Now that apple has released SwiftUI & Combine are there any initiatives to port this project from RxSwift to Combine?

**Comment by twittemb** [comment]
Hi @paulmeyerle 

It is a good question :-)

It could make sens to have a "CombineFlow" BUT with it would have a limited future since SwiftUI will gain in strength in the years to come, bringing other paradigms of navigation.

If there is a CombineFlow, it might be made differently than RxFlow in order to match the SwiftUI constraints.

Short answer: I'm not considering a Combine version right now but I'm totally opened to the discussion and any help that would come from it.
