### ISSUE TITLE
What is Flowable.noFlow?

### ISSUE THREAD

**Issue by sirvon** [RxSwiftCommunity/RxFlow#15]
When this is returned, what does this mean?

```swift
return Flowable.noFlow
```

**Comment by twittemb** [comment]
Hi @sirvon 

As you can see in the last version of the branch 'develop', it is now NavigationItem.noNavigation.

I think it is more explicit, you can take a look at my blog for a detail explanation of all the concepts behind RxFlow (https://twittemb.github.io/swift/coordinator/reactive/rxflow/reactive%20programming/2017/12/09/rxflow-part-2-in-practice/)

To make it short it means that at some point in a Flow, your navigation cannot go further. For instance in a UINavigationController, after you stack the last screen, the only thing you can do is going back in the previous screen. This back action is handled by the system, not by the developper. Knowing this, when you build this last screen in your Flow, you will return an empty array of NavigationItems, because nothing can produce more steps at this point. Nothing will be registered in the Coordinator as a nextStepper. And this empty array is exactly what NavigationItem.noNavigation is.

I hope this is clearer now ?

**Comment by twittemb** [comment]
@sirvon 

Is that ok with you ?

**Comment by sirvon** [comment]
wow! yes, sir!
