### ISSUE TITLE
Flows.whenReady -> variable naming

### ISSUE THREAD

**Issue by benjohnde** [RxSwiftCommunity/RxFlow#37]
I just wondered if there exists a specific reason for naming the variable in the function `Flows.whenReady` `flow1` and not just `flow` for convenience? :)

I fully understand the notion when it comes to more than one flow.

We wrote a very little extension for that, cause we found it fresher to read:

```
extension Flows {
    public static func whenReady<RootType: UIViewController> (flow: Flow, block: @escaping (_ flowRoot: RootType) -> Void) {
        whenReady(flow1: flow, block: block)
    }
}
```

**Comment by twittemb** [comment]
Hi @benjohnde 

Thanks for your feedback. I must say that at first I had named this function the way you wish (flow instead of flow1) ...

I changed it just for Xcode to present the autocompletion in the right order :-(

Changing it now would be a breaking change for developers who already use RxFlow :-(

We could add the new signature beside the existing one but it would be weird to have 2 functions doing the same thing ...

What is your opinion on that ?

**Comment by benjohnde** [comment]
That's a very good reason for naming the function as they are right now. Thanks for pointing that out.

![untitled](https://user-images.githubusercontent.com/5439810/36854473-6321323a-1d71-11e8-97ae-00ef724d87b4.png)

That's how it looks in my Xcode. Well, for sure opinions will differ and mine is very weak, but for us using:

```
static func whenReady<RootType: UIViewController> (flow: Flow, block: @escaping (_ flowRoot: RootType) -> Void)
static func whenReady<RootType>(flows: [Flow], block: @escaping ([RootType]) -> Swift.Void) where RootType : UIViewController
```

is enough and quite precise.

Is there an actual need or an advantage to use the ones with `flow1, flow2, ...` instead of the `[Flow]` array?

Breaking an API is always a thing, but in this very new library, I think it is okay to optimize a bit.

**Comment by twittemb** [comment]
There is one real advantage to use ones with flow1, flow2, ... instead of the [Flow] array.

You can take advantage of generic functions and type inference. For instance you could write:
```swift
Flows.whenReady (flow1: flow1, flow2: flow2) { (root1: UINavigationController, root2: UITabbarController) in
.....
}
```

As you know the types of each flow roots, you can "force" the compiler to give it back to you in the parameters.

In the "array" signature, You will just know that roots are UIViewController (or a subtype) and you will have to cast each of them in the type you know they are. 

Also, I wanted to mimic the behavior of RxSwift library, for instance Observable.combineLatest offers the same kind of function signatures.

**Comment by twittemb** [comment]
Is it ok to close this issue @benjohnde ?

**Comment by benjohnde** [comment]
We do not use UITabBarController and for us it is (well, at least until now) absolutely sufficient to use UIViewController on root for presenting/dismissing views. But I can see where you are coming from, thanks for the insights. Absolutely, this one can be closed.
