### ISSUE TITLE
Other Types of Steppers Impl

### ISSUE THREAD

**Issue by sirvon** [RxSwiftCommunity/RxFlow#4]
Thanks for this library, coming at a great time.

> (for instance when we only need to bootstrap a Flow with a first Step and don't want to code a basic Stepper for that)

Where is the documentation on coding a basic Stepper?

**Comment by twittemb** [comment]
Hi @sirvon 
Thanks for your feedback. Actually, there is no precise documentation on coding a basic Stepper.
As Stepper is a Protocol, there is no rule to follow but fulfill the Protocol requirements.

Either a Stepper is made to emit Steps in response to user events (it is the case in the demo app with WatchedViewModel and the pick function), Or it is made to emit Steps in response to other application layers.

We could imagine that when we launch a Flow with a Stepper, instead of being a OneStepper we could have a custom Stepper doing a network request every 10s to check if the user's session is alive. And if the session is dead, a login Step is emitted.

```swift
class WishlistFlowStepper: Stepper, HasDisposeBag {

    init() {

        // this is the first step
        self.step.onNext(DemoStep.movieList)

        // we test every 10s that the session is alive. If it is not, a login screen pops up
        Observable<Int>.interval(10, scheduler: MainScheduler.instance).map({ (_) -> Bool in
            // Check the session here
            return false
        }).subscribe(onNext: { [unowned self] (alive) in
            if !alive {
                // session is dead, user has to login again
                self.step.onNext(DemoStep.login)
            }
        }).disposed(by: self.disposeBag)
    }
}
```

Is it what you were looking for ?

**Comment by twittemb** [comment]
hi @sirvon 

I hope you had time to look at my answer. I'd be happy to discuss about that.

If you are ok with my explanations, let me know so that I can close this issue.

Thanks.

**Comment by sirvon** [comment]
Thank you, for your depth.

Your example above has shown me, it's possible to have application logic in the stepper.

I was just trying to understand, constructing a stepper in general. This example and the steppers inside the flows give me more clarity.

So a Stepper can wrapper other functionality pertaining the particular flow its about to enter.
So you can Authtenticate that flow, what else can you imagine doing in the stepper.

Also, how else can that Rx be implemented with a timer. Was thinking about using a promise function.

**Comment by twittemb** [comment]
Hi @sirvon 
I don't know much about promise functions, but as far as I know I can't see anything that would not be possible in a Stepper.

For me a Stepper is something that represents the navigation state within the app.  There are 2 kinds of Stepper: the one that is attached directly to a Flow and the ones that are attached to the Presentables inside the Flow.

We could imagine that a "Flow attached" Stepper should have to decide which would be the appropriate first Step in a Flow, according to business rules.

A "Presentable attached" Stepper could be implemented in ViewModels (in MVVM), Controllers (in MVC), Presenters (in MVP).

In many of my apps, a case happens a lot: Display the Login screen whenever the user looses its session (in case of a web backend for instance). The Stepper of the first Flow has to listen to this session state (that could be managed by a low level layer such as a NetworkManager), and when the session state emits a "NOT_CONNECTED" event, you just have to pop up the login screen. It is pretty cool because you handle that at the "Flow". Other UIViewControllers do not have to care about that.

There must be plenty of cases I am not thinking about, and RxFlow will probably have to be modified to fit these cases. PR are very welcome.

If you think I have answered your questions, let me know so I can close the issue.

Bye.
