### ISSUE TITLE
Root window emit the completed event immediately after be shown

### ISSUE THREAD

**Issue by dmanuelcl** [RxSwiftCommunity/RxFlow#45]
Hi in my current project I need to swap between 2 Flows attached to the root Window, in the main flow I keep checking the user signing status to decide if in need show one flow or other , but when I try to swap between flows the steps emited from the main flow are ignored becouse the ``` window.rxVisible``` emit ```completed``` just after the window become keyAndVisible so the cordinator ignores that steps

**Comment by twittemb** [comment]
Hi @dmanuelcl 

Have you checked the demo app because this is what I do in it -> switching between 2 flows for the UIWindow.

**Comment by dmanuelcl** [comment]
HI @twittemb 
Thanks for your quick response, based on the demo is that I am implementing this functionality in my project, below fragments of my code

**AppDelegate**

````swift
 self.mainFlow = MainFlow(withWindow: window, andServicesProvider: servicesProviderInstance)
        self.coordinator.coordinate(flow: self.mainFlow, withStepper: self.mainFlow)
````


**MainFlow**

````swift

  init(withWindow rootWindow: UIWindow, andServicesProvider: ServicesProviderType){
   //Some code here
   self.checkUserSignInStatus()
}

    func checkUserSignInStatus(){
           self.securityService.isSignIn
            .distinctUntilChanged()
            .subscribe(onNext: { (isSignIn) in
                if isSignIn {
                   self.step.accept(MainSteps. login)
                }else{
                  self.step.accept(MainSteps.dashboard)
               }
            }).disposed(by: self.disposeBag)
   }

    func navigate(to step: Step) -> NextFlowItems {
        if let step = step as? MainSteps{
            switch step{
            case .login:
                return self.navigateToLoginFlow()
            case .dashboard:
                return self.navigateDashboardAppFlow()
            }
        }
        return  NextFlowItems.none
    }

     func self.navigateToLoginFlow() -> NextFlowItems{
        let flow = LoginFlow(securityService: self.securityService)
        Flows.whenReady(flow1: flow) { (flowRoot) in
            self.rootWindow.rootViewController = flowRoot
        }
        return .one(flowItem: NextFlowItem.init(nextPresentable: flow, nextStepper: flow.stepper))
    }

    func navigateToDashboardFlow() -> NextFlowItems{
        let flow = DashboardFlow()
        Flows.whenReady(flow1: flow) { (flowRoot) in
            self.rootWindow.rootViewController = flowRoot
        }
        return .one(flowItem: NextFlowItem.init(nextPresentable: flow, nextStepper: flow))
    }

````

if the user's session changes, update the flow to show the corresponding views, everything works at the first moment and the correct flow is shown, if in the future the user's status changes, the step is issued correctly but the cordinator ignores it, I have the solution on my fork, I can do a pull request

**Comment by twittemb** [comment]
Hi @dmanuelcl 

Thanks for this feedback. Indeed this is a potential issue. I cherry-picked the commit that fixes that in your PR: https://github.com/RxSwiftCommunity/RxFlow/pull/46
Unfortunately I couldn't merge your PR because the develop branch history has been overwritten since your PR, there were conflicts). But your code is in develop now.

Although there was an issue, I think you shouldn't swap your flows at any time (when a user is logged out) during the user navigation. I assume he could be somewhere in your Dashboard or so ever and when logged out, he would be abruptly be displayed the login Flow ?

I think it would be a better idea to display a modal login popup. For instance in your Dashboard Flow you could listen to the login state (as you do for now in the MainFlow) and react to the "login" step by presenting a login popup.

What do you think about that ?

**Comment by dmanuelcl** [comment]
I'm going to check what you tell me, but I have to adjust to the design and flow defined, likewise the transition between flow I do it with animation, thanks for the suggestions
