### ISSUE TITLE
Navigate to next item within a flow

### ISSUE THREAD

**Issue by iOSDevFin** [RxSwiftCommunity/RxFlow#67]
Hi there,

I was wondering if it is possible to navigate to the next flow item with a simple call like step.next. As far as I know and tried out several things, I always have to know what the next step should be. We have a big onboarding navigation where we just want to set the order of the steps within the step enum and then just want to call step.next or something similar. 

Any ideas?

Many thanks,
FinDev

**Comment by twittemb** [comment]
Hi @iOSDevFin 

Thanks for reaching.

You could have a generic step (AppStep.next) and trigger it in every stepper of your Flow -> self.steps.accept(AppStep.next).

You would have to handle the state of your onboarding within your Onboarding flow in order to know what to do when you receive .next in the navigate function.

You could even do an extension on BehaviorRelay (this is the type of the "steps" property of a Stepper) to make it easier.

extension BehaviorRelay {
    func next () {
        self.accept(AppStep.next)
    }
}

In your Stepper you only have to call: self.steps.next()

I hope this helps.

**Comment by iOSDevFin** [comment]
Yep we've made it like this and worked. Many thanks for the suggestion.

**Comment by twittemb** [comment]
Great !

I close the issue then.
