### ISSUE TITLE
Always visible floating view and it's Steps

### ISSUE THREAD

**Issue by Jauzee** [RxSwiftCommunity/RxFlow#71]
We have a view in our app, which is visible on each screen. This view can present some views modally or push them onto the navigation stack.

Any advice on how to create Flows in this scenario? It would be nice if all steps from this floating view would be handled by some RootFlow from where all the other views are presented, so the RootFlow would dismiss everything and present new view if needed.

**Comment by twittemb** [comment]
Hi @Jauzee 

Having a RootFlow that takes care of the presentation of global Modal ViewControllers is great. For instance a RootStepper can listen to the user authentication state and trigger a step every time the user is logged out, so the RootFlow would present a modal login screen.

Could you give me more details about your Flows organization ? because the main advantage of flow coordination is that each Flow is sandboxed and is only responsible what a limited number of things ... what you want to do is "trigger some kind of global step from whatever Stepper, this global Step could be catched be the RootFlow and the RootFlow would display a modal or push a VC on the navigation stack" ? What bothers me here is that a RootFlow could push a new VC on a Navigation Stack it is not responsible for ...

You could achieve that by having a centralized state in your app that could be mutated by your view (the one that is embedded every where) and your RootStepper could listen to this State (let's say you have on Observable<State> somewhere) and display a Modal or push a VC ... Still I am concerned about pushing a new VC on a Stack that does not belong to the RootFlow !

If you could share more details about your Flows perhaps I could help a little more.

**Comment by Jauzee** [comment]
> "trigger some kind of global step from whatever Stepper, this global Step could be catched by the RootFlow and the RootFlow would display a modal or push a VC on the navigation stack"

Exactly! This works until I present `NextFlowItem` where `Presentable` is `Flow` subclass, not `UIViewController`. The `RootFlow` stops receiving `Step`s until the new `Flow` is dismissed.

Currently all the _FloatingView_'s `Step`s are handled by the `RootFlow` — I pass _FloatingView's_ `Stepper` in a `CompositeStepper` to each `NextFlowItems` returned in the `RootFlow`.

The _FloatingView_ also presents new `Flow`s, not just one-screen modals.

Handling all the `Step`s related to the _FloatingView_ in the `RootFlow` is ok for us, because all the new `Flow`s either presented modally or pushed from there, so if new `Step` come from _FloatingView_ the `RootFlow` will dismiss presented modal view (if any) and present new one.

RE to _centralized state_: will this work for us if we need to handle all the flows by the `Coordinator`? We have a `FlowObserver` class which does some work based on the presented `Flow` in the `Coordinator` (willNavigate, didNavigate).
And one more question about a _Gloabal State_ handled by the `RootStepper`: if the `RootFlow` stops receiving further `Step`s if another `Flow` is presented, does it make sense at all?

----

While writing this message and trying to explain what's going on in my `Flow`s I realized that I just should `triggerParentFlow` with the _FloatingView_ `Step` from a `Flow` that presented from the `RootFlow` and this will totally solve the problem. Decided to publish this message, maybe it'll be helpful for someone.

**Comment by twittemb** [comment]
As you have found a solution, I close this issue.

Thanks for sharing your idea !
