### ISSUE TITLE
What is the need to initialize all the services in AppDelegate?

### ISSUE THREAD

**Issue by alchemistgo87** [RxSwiftCommunity/RxFlow#77]
In the Demo app, all the services are being initialised in the AppDelegate and all the services are being passed to all the flows, even if it is not required by some flows. So, I just wanted to ask that what would be the best way to initialise and pass only the required services in a flow?

Thank you.

**Comment by twittemb** [comment]
Hi @alchemistgo87 

Your question deals with Dependency Injection. Flows (and Coordinator Pattern) are great to do DI. My solution is pretty naive because I pass an AppServices to Flows and that AppServices contains all the Services. Protocol composition (Has{Service}) allows me do segregate the AppServices to really needed services in the low level layers.

You could pass to the Flows only what is needed by the lower level layers (ViewModels). You could use some frameworks like Swinject to help you do that. In that case you would give the "dependency container" to the Flows and then let the container help you resolve your dependencies.

I hope this helps.

**Comment by alchemistgo87** [comment]
That sounds correct. Thank you for the response @twittemb!
