### ISSUE TITLE
Presenting a navigation controller

### ISSUE THREAD

**Issue by fenixsolorzano** [RxSwiftCommunity/RxFlow#83]
I'm having trouble when presenting a `uinavigationcontroller` from a `uiviewcontroller` instantiated from a `Flow`.

I got a `LogInController` that is the stepper itself, I'm using Facebook AccountKit for my login process, to use it I have to present their controller from my login controller.

```swift

// At Login Flow

...

private func login() -> NextFlowItems {
        
        let controller = LogInController.instantiate()
        let item = NextFlowItem(
            nextPresentable: controller,
            nextStepper: controller)
        
        rootViewController.pushViewController(controller, animated: true)
        
        return NextFlowItems.one(flowItem: item)
    }

...

// At LoginController

@IBAction func logIn(_ sender: UIButton) {
        present(accountKitController as! UIViewController, animated: true)
}

``` 

AccountKit has a delegate to handle login completion, and I'm trying to send the step from there.

```swift

func viewController(_ viewController: (UIViewController & AKFViewController)!, didCompleteLoginWith accessToken: AKFAccessToken!, state: String!) {
        
        self.accountKit.requestAccount {
           
            ...
            
            if self.accountKitForSignUp {
                // This is reached but does not arrive to `navigate(to:)` at the Flow class
                self.step.accept(AuthStep.createAccount(email: email)) 
            }
            else {
                self.step.accept(AuthStep.recoverPassword)
            }
        }
    }

```

I don't understand why `navigate` isn't reached.

**Comment by twittemb** [comment]
Hi @felixsolorzano 

The only reason why navigate() is not called would be because the LoginViewController is maybe under the AccountKitController.

With RxFlow, when a Stepper triggers a new Step, it will be processed ONLY if the associated Presentable is displayed (ie no other ViewCcontroller on the top of the hierarchy).

What you could do:

- do not present the AccountViewController in the LoginViewController if possible. Instead the LoginViewControler could trigger a Step "wantToLogin" and the navigate() will be called so you can present the AccountViewController.

- when navigating to the AccountViewController, you will return a "NextFlowItems" containing the accountViewController as a Presentable and a Stepper that will also be the delegate of the AccountViewController.

- when the delegate is called back, as it is a Stepper, you will trigger a Step "loginComplete" that will make the navigate() function be called.

- you can then present a next screen or a next flow.

Does this seem correct ?

**Comment by felixsolorzano** [comment]
I'll tryout and will let you know how it goes. Thanks.

**Comment by twittemb** [comment]
Hi @felixsolorzano 

Any updates on this ? :-)

**Comment by twittemb** [comment]
Hi @felixsolorzano 

Can I close this issue ?

**Comment by twittemb** [comment]
Hi @fenixsolorzano 

There hasn't been any updates here for a while. I close the issue.

Feel free to reach out in case you have questions.
