### ISSUE TITLE
Doesn't work with Peek & Pop gesture

### ISSUE THREAD

**Issue by av0c0der** [RxSwiftCommunity/RxFlow#85]
I did implement the gesture in our app and faced the bug: the app won't continue the navigation process. Reproduced with the demo app.
<img width="975" alt="screen shot 2018-10-10 at 15 33 35" src="https://user-images.githubusercontent.com/7991920/46739934-e9da5100-cca1-11e8-9c2f-606cf2445415.png">

**Comment by Jauzee** [comment]
Hi @twittemb. Sorry for the late response, I missed your message.

I forked the repo and changed the `WishlistViewController.swift` file here: https://github.com/Jauzee/RxFlow/tree/develop

**Comment by twittemb** [comment]
Thanks for your repo @Jauzee 

In the current version, RxFlow is not suited for peek n pop usage. 

In the RxFlow philosophy the ViewControllers are created by the Flows.
Peek n pop needs to implement the creation of the destination ViewController in its delegate (aka the WishlistViewController) ... unfortunately it is not compatible with the current implementation of RxFlow.

I can't see a good way to do this because the aim of the Coordinator pattern is that hide the ViewControllers creation from the previous ViewControllers.

Do you have a good idea on this ?

**Comment by Jauzee** [comment]
@twittemb no, I didn't investigate it yet. 

In our app I only create a view controller for the preview. So in the delegate callback I only call some method, which triggers new step in a Flow. I can't understand why the Flow doesn't receive further steps. It opens the view controller which was previewed, but then the navigation stops.

**Comment by Jauzee** [comment]
Hi @twittemb. I understand that, but you can commit any view controller, you're not limited to present the view controller that was created for a preview. You can just throw it out and call your new Step, so I believe there's a way to handle this. Can you please explain a little why it doesn't handle new Steps, what's the key difference here?

**Comment by Jauzee** [comment]
Hi @twittemb!

Commenting this [line](https://github.com/RxSwiftCommunity/RxFlow/blob/develop/RxFlow/Coordinator.swift#L173) _resolves_ the problem. Why it can be a problem in this case?

**Comment by ssaluk** [comment]
@Jauzee Hi! I registered another [issue](https://github.com/RxSwiftCommunity/RxFlow/issues/89), which I traced to the same line in Coordinators.swift but with different observed effect (missing section title in some tables). As it turned out my problem was I didn't clear the existing delegate/datasource for tables (debug version of RxSwift has the asserts for this, but I was using release version). Just my $.02

**Comment by Jauzee** [comment]
Thank you very much for your feedback @ssaluk. It can be helpful.

**Comment by dsk1306** [comment]
You can actually emit steps, but after some delay.
I just tried

```swift
    func previewingContext(_ previewingContext: UIViewControllerPreviewing, commit viewControllerToCommit: UIViewController) {
        Observable<Void>.just(())
            .delay(0.5, scheduler: MainScheduler.asyncInstance)
            .map { _ in AppStep.transactionDetail }
            .bind(to: viewModel.step)
            .disposed(by: disposeBag)
    }
```

and and didn't stop navigation process.
