### ISSUE TITLE
Step to AppFlow

### ISSUE THREAD

**Issue by MortMerr** [RxSwiftCommunity/RxFlow#86]
I have a case, when i am really deep in flows hierarchy and i want dispatch a step to AppFlow.

Concrete case: 
UITabBarController has UINavigationController (flow 1) as a tab. This tab has button, which presents another viewController (flow 2). In this flow i have the tableView, which cellClick push new viewController, which has button, which presents another viewController (flow 3).
I hope, that u get it :) And in the flow 3 i want to dispatch step, which will navigate to another tab of tabBarController. This step will be handled in appflow with code like
```
tabBarController.selectedIndex = 1
```

So, i want to dispatch this step directly to Appflow, without inserting `case triggerParentFlow (withStep: Step)` in flow3 and flow2 `navigate` method.

If my logic is weird, then please tell me your opinion.

P.S. My other question to you - why not make `Flow` generic (with associated type), because 
`guard let step = step as? YOUR_SUPER_MASSIVE_ENUM_WITH_STEPS else { return .none }`
in every flow looks weird.

**Comment by twittemb** [comment]
Hi @MortMerr 

Perhaps you can use .triggerParentFlow (withStep: Step) from Flow2 to Flow2 to Flow1. The other solution is to pass the Flow1 stepper to your children flows.

Why Flow is not a protocol with associated type ? because the FlowCoordinator has a property of type Flow. And this is not possible to have a property of a protocol type that has an associated type. I tried to play with Type Erasure but it was not satisfying in my case.

**Comment by MortMerr** [comment]
@twittemb 1) yeah, i handle it like that. I just thought, that there is better way.
2) ok. thank u for clarification
Issue could be closed
